### Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation.

In [67]:
import torch
import numpy as np

### Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

<b> - Directly from data</b>

Tensors can be created directly from data. The data type is automatically inferred.

In [68]:
data = [[1,2], [3,4]]
x = torch.tensor(data)

In [69]:
x

tensor([[1, 2],
        [3, 4]])

<b>- From a NumPy array</b>

Tensors can be created from NumPy arrays

In [70]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [71]:
x_np

tensor([[1, 2],
        [3, 4]])

<b>- From another tensor:</b>

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [72]:
x_ones = torch.ones_like(x) # retains the properties of x
print(f"Ones Tensor:\n {x_ones}")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])


In [73]:
x_zeroes = torch.zeros_like(x) # retains the properties of x
print(f"Zeroes Tensor:\n {x_zeroes}")

Zeroes Tensor:
 tensor([[0, 0],
        [0, 0]])


In [74]:
x_rand = torch.rand_like(x, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor:\n {x_rand}")

Random Tensor:
 tensor([[0.2451, 0.9213],
        [0.3883, 0.1511]])


<b>- With random or constant values:</b>

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [75]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeroes_tensor = torch.zeros(shape)

print(f"Random Tensor:\n {rand_tensor}")
print(f"Ones Tensor:\n {ones_tensor}")
print(f"Zeroes Tensor:\n {zeroes_tensor}")

Random Tensor:
 tensor([[0.7450, 0.9209, 0.6663],
        [0.8294, 0.1131, 0.5118]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeroes Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [76]:
tensor = torch.rand(3,4)

print(f"Shape of the Tensor: {tensor.shape}")
print(f"Datatype of the Tensor: {tensor.dtype}")
print(f"Device Tensor is stored on: {tensor.device}")

Shape of the Tensor: torch.Size([3, 4])
Datatype of the Tensor: torch.float32
Device Tensor is stored on: cpu


### Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here: https://pytorch.org/docs/stable/torch.html

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [77]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

<b>Standard numpy-like indexing and slicing:</b>

In [78]:
tensor = torch.rand(4,4)
tensor

tensor([[0.0521, 0.6583, 0.5164, 0.4201],
        [0.7206, 0.6321, 0.0590, 0.1817],
        [0.2112, 0.9927, 0.2480, 0.3550],
        [0.8818, 0.6451, 0.8547, 0.5782]])

In [79]:
print(f"First Row:\n {tensor[0]}")

First Row:
 tensor([0.0521, 0.6583, 0.5164, 0.4201])


In [80]:
print(f"First Column:\n {tensor[:,0]}")

First Column:
 tensor([0.0521, 0.7206, 0.2112, 0.8818])


In [81]:
print(f"Last Column:\n {tensor[:,-1]}")

Last Column:
 tensor([0.4201, 0.1817, 0.3550, 0.5782])


In [82]:
# we can also change a row or column data using below operation
tensor[:,1] = 0
tensor

tensor([[0.0521, 0.0000, 0.5164, 0.4201],
        [0.7206, 0.0000, 0.0590, 0.1817],
        [0.2112, 0.0000, 0.2480, 0.3550],
        [0.8818, 0.0000, 0.8547, 0.5782]])

### Joining tensors:

 You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining operator that is subtly different from torch.cat.

In [83]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) # stack vertically
t1

tensor([[0.0521, 0.0000, 0.5164, 0.4201],
        [0.7206, 0.0000, 0.0590, 0.1817],
        [0.2112, 0.0000, 0.2480, 0.3550],
        [0.8818, 0.0000, 0.8547, 0.5782],
        [0.0521, 0.0000, 0.5164, 0.4201],
        [0.7206, 0.0000, 0.0590, 0.1817],
        [0.2112, 0.0000, 0.2480, 0.3550],
        [0.8818, 0.0000, 0.8547, 0.5782],
        [0.0521, 0.0000, 0.5164, 0.4201],
        [0.7206, 0.0000, 0.0590, 0.1817],
        [0.2112, 0.0000, 0.2480, 0.3550],
        [0.8818, 0.0000, 0.8547, 0.5782]])

In [84]:
t2 = torch.cat([ones_tensor, ones_tensor, ones_tensor], dim=1) # stack horizontally
t2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Tensor Operations

Tensor operations are mathematical operations that can be performed on tensors to manipulate and transform their values. PyTorch provides a wide range of tensor operations that can be used to perform basic operations like arithmetic, statistical, and logical operations on tensors.

In [85]:
# create a 2d tensor
tensor = torch.ones(2,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

<b> - Addition</b>

Tensor addition can be performed using the torch.add() function or the + operator.

In [86]:
a = torch.add(tensor,5)
a

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [87]:
a = tensor + 5
a

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.]])

<b> - Subtraction</b>

Tensor subtraction can be performed using the torch.sub() function or the - operator.

In [88]:
b = torch.sub(a,1)
b

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [89]:
b = a-1
b

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

<b> - Multiplication</b>

Tensor multiplication can be performed using the torch.mul() function or the * operator.

In [90]:
c = torch.mul(a,b)
c

tensor([[30., 30., 30., 30.],
        [30., 30., 30., 30.]])

In [91]:
c = a * b
c

tensor([[30., 30., 30., 30.],
        [30., 30., 30., 30.]])

<b> - Division</b>

Tensor division can be performed using the torch.div() function or the / operator.

In [92]:
d = torch.div(c,10)
d

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [93]:
d = c/10
d

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

### Advanced Tensor Operations

Advanced tensor operations include matrix multiplication, transposition, reshaping, and concatenation that basically deals with 2D tensors.

<b> - Matrix Multiplication</b>

We can perform Matrix multiplication using the torch.mm() function or the @ operator.

In [94]:
# create a 2d tensor
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

In [95]:
A

tensor([[1, 2],
        [3, 4]])

In [96]:
B

tensor([[5, 6],
        [7, 8]])

In [97]:
C = torch.mm(A,B)
C

tensor([[19, 22],
        [43, 50]])

In [98]:
C = A @ B
C

tensor([[19, 22],
        [43, 50]])

<b> - Transposition</b>

Transposition in tensor operations is the process of flipping the axes of a tensor. It involves exchanging the rows and columns of a 2D tensor or more generally, the axes of a tensor of any dimension.

We can perform Transposition using the torch.t() function.

In [99]:
tensor = torch.ones(3,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
D = torch.t(tensor)
D

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

<b> - Reshaping</b>

Reshaping in tensor operations is the process of changing the shape or dimensions of a tensor while preserving its underlying data. It involves rearranging the elements of a tensor to fit a new shape, without changing the total number of elements.

We can perform Reshaping using the torch.reshape() function or the .view() method.

In [101]:
E = torch.reshape(D, (3,4))
E

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
E = A.view(1, 4)
E

tensor([[1, 2, 3, 4]])

<b> - Tensor to NumPy array</b>

In [103]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [104]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [105]:
# Normal Distribution

X = torch.rand(size=(3,4)).normal_(mean=0, std=1)
X

tensor([[-0.3057,  0.1206,  0.0470, -0.5111],
        [-0.3934, -1.2435,  0.2780, -0.4756],
        [-1.8124, -1.1113,  1.6001,  0.1390]])

In [106]:
# Uniform Distribution

U = torch.rand(size=(3,4)).uniform_(4,7)
U

tensor([[5.9002, 5.7010, 4.8736, 6.4109],
        [6.5800, 5.7002, 5.8851, 4.6181],
        [5.3523, 6.7528, 4.7439, 4.2890]])

In [107]:
# Diagonal Matrix

DM = torch.diag(torch.ones(8))
DM

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])

In [108]:
DM.shape

torch.Size([8, 8])

In [109]:
DM = torch.diag(7*torch.ones(8))
DM

tensor([[7., 0., 0., 0., 0., 0., 0., 0.],
        [0., 7., 0., 0., 0., 0., 0., 0.],
        [0., 0., 7., 0., 0., 0., 0., 0.],
        [0., 0., 0., 7., 0., 0., 0., 0.],
        [0., 0., 0., 0., 7., 0., 0., 0.],
        [0., 0., 0., 0., 0., 7., 0., 0.],
        [0., 0., 0., 0., 0., 0., 7., 0.],
        [0., 0., 0., 0., 0., 0., 0., 7.]])

In [110]:
# Sum of a matrix
torch.sum(DM)

tensor(56.)

In [111]:
# Maximum value in the matrix
torch.max(U)

tensor(6.7528)

In [112]:
# Minimum value in the matrix
torch.min(U)

tensor(4.2890)

In [113]:
U

tensor([[5.9002, 5.7010, 4.8736, 6.4109],
        [6.5800, 5.7002, 5.8851, 4.6181],
        [5.3523, 6.7528, 4.7439, 4.2890]])

In [114]:
# Column-wise and Row-wise minimum and maximum value in the matrix

print(f"Column-wise maximum value:\n {torch.max(U, dim=0)}") #column
print()
print(f"Column-wise minimum value:\n {torch.min(U, dim=0)}")
print()
print(f"Row-wise maximum value:\n {torch.max(U, dim=1)}") # Row
print()
print(f"Row-wise maximum value:\n {torch.min(U, dim=1)}")
print()

Column-wise maximum value:
 torch.return_types.max(
values=tensor([6.5800, 6.7528, 5.8851, 6.4109]),
indices=tensor([1, 2, 1, 0]))

Column-wise minimum value:
 torch.return_types.min(
values=tensor([5.3523, 5.7002, 4.7439, 4.2890]),
indices=tensor([2, 1, 2, 2]))

Row-wise maximum value:
 torch.return_types.max(
values=tensor([6.4109, 6.5800, 6.7528]),
indices=tensor([3, 0, 1]))

Row-wise maximum value:
 torch.return_types.min(
values=tensor([4.8736, 4.6181, 4.2890]),
indices=tensor([2, 3, 3]))



In [115]:
# indices of the max and min value
print("Indices of max value:\n torch.argmax(U)")
print()
print("Indices of min value:\n torch.argmin(U)")

Indices of max value:
 torch.argmax(U)

Indices of min value:
 torch.argmin(U)


In [116]:
# average value

print(f"Average of Tensor: {torch.mean(U)}")
print()
print(f"Average Column-wise: {torch.mean(U, dim=0)}")
print()
print(f"Average Row-wise: {torch.mean(U, dim=1)}")

Average of Tensor: 5.567246913909912

Average Column-wise: tensor([5.9442, 6.0513, 5.1675, 5.1060])

Average Row-wise: tensor([5.7214, 5.6958, 5.2845])


In [117]:
# compare tensors

C = torch.rand(3,4)
C

tensor([[0.7067, 0.9381, 0.0189, 0.1747],
        [0.1682, 0.0473, 0.5458, 0.0316],
        [0.6660, 0.7857, 0.9581, 0.2023]])

In [118]:
torch.eq(U,C)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [119]:
torch.eq(C,C)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])