### Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation.

In [3]:
import torch
import numpy as np

### Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

<b> - Directly from data</b>

Tensors can be created directly from data. The data type is automatically inferred.

In [4]:
data = [[1,2], [3,4]]
x = torch.tensor(data)

In [5]:
x

tensor([[1, 2],
        [3, 4]])

<b>- From a NumPy array</b>

Tensors can be created from NumPy arrays

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_np

tensor([[1, 2],
        [3, 4]])

<b>- From another tensor:</b>

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [8]:
x_ones = torch.ones_like(x) # retains the properties of x
print(f"Ones Tensor:\n", {x_ones})

Ones Tensor:
 {tensor([[1, 1],
        [1, 1]])}


In [9]:
x_zeroes = torch.zeros_like(x) # retains the properties of x
print(f"Zeroes Tensor:\n", {x_zeroes})

Zeroes Tensor:
 {tensor([[0, 0],
        [0, 0]])}


In [10]:
x_rand = torch.rand_like(x, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor:\n", {x_rand})

Random Tensor:
 {tensor([[0.8794, 0.6617],
        [0.3289, 0.3907]])}


<b>- With random or constant values:</b>

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeroes_tensor = torch.zeros(shape)

print(f"Random Tensor:\n", {rand_tensor})
print(f"Ones Tensor:\n", {ones_tensor})
print(f"Zeroes Tensor:\n", {zeroes_tensor})

Random Tensor:
 {tensor([[0.0221, 0.8269, 0.2179],
        [0.1134, 0.9804, 0.4494]])}
Ones Tensor:
 {tensor([[1., 1., 1.],
        [1., 1., 1.]])}
Zeroes Tensor:
 {tensor([[0., 0., 0.],
        [0., 0., 0.]])}


### Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [13]:
tensor = torch.rand(3,4)

print(f"Shape of the Tensor:", {tensor.shape})
print(f"Datatype of the Tensor:", {tensor.dtype})
print(f"Device Tensor is stored on:", {tensor.device})

Shape of the Tensor: {torch.Size([3, 4])}
Datatype of the Tensor: {torch.float32}
Device Tensor is stored on: {device(type='cpu')}


### Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here: https://pytorch.org/docs/stable/torch.html

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [14]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

<b>Standard numpy-like indexing and slicing:</b>

In [23]:
tensor = torch.rand(4,4)
tensor

tensor([[0.3615, 0.0318, 0.1010, 0.0969],
        [0.3229, 0.2077, 0.3341, 0.4077],
        [0.3685, 0.2071, 0.4613, 0.2685],
        [0.6311, 0.0321, 0.9253, 0.9157]])

In [24]:
print(f"First Row:\n", {tensor[0]})

First Row:
 {tensor([0.3615, 0.0318, 0.1010, 0.0969])}


In [25]:
print(f"First Column:\n", {tensor[:,0]})

First Column:
 {tensor([0.3615, 0.3229, 0.3685, 0.6311])}


In [26]:
print(f"Last Column:\n", {tensor[:,-1]})

Last Column:
 {tensor([0.0969, 0.4077, 0.2685, 0.9157])}


In [27]:
# we can also change a row or column data using below operation
tensor[:,1] = 0
tensor

tensor([[0.3615, 0.0000, 0.1010, 0.0969],
        [0.3229, 0.0000, 0.3341, 0.4077],
        [0.3685, 0.0000, 0.4613, 0.2685],
        [0.6311, 0.0000, 0.9253, 0.9157]])

### Joining tensors:

 You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining operator that is subtly different from torch.cat.

In [28]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) # stack vertically
t1

tensor([[0.3615, 0.0000, 0.1010, 0.0969],
        [0.3229, 0.0000, 0.3341, 0.4077],
        [0.3685, 0.0000, 0.4613, 0.2685],
        [0.6311, 0.0000, 0.9253, 0.9157],
        [0.3615, 0.0000, 0.1010, 0.0969],
        [0.3229, 0.0000, 0.3341, 0.4077],
        [0.3685, 0.0000, 0.4613, 0.2685],
        [0.6311, 0.0000, 0.9253, 0.9157],
        [0.3615, 0.0000, 0.1010, 0.0969],
        [0.3229, 0.0000, 0.3341, 0.4077],
        [0.3685, 0.0000, 0.4613, 0.2685],
        [0.6311, 0.0000, 0.9253, 0.9157]])

In [30]:
t2 = torch.cat([ones_tensor, ones_tensor, ones_tensor], dim=1) # stack horizontally
t2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])